// Copy contract ABIs from Foundry build output into the frontend as typed TS modules.
// Run after `forge build` (dev-local.sh does this for you).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "contracts/out");
const dest = join(root, "frontend/src/abi");
const contracts = ["Registry", "PayoutRouter", "IdentityAttestor", "FeeVaultFactory", "FeeVault", "ILaunchpadAdapter"];

mkdirSync(dest, { recursive: true });
for (const name of contracts) {
  const { abi } = JSON.parse(readFileSync(join(out, `${name}.sol/${name}.json`), "utf8"));
  const body = `// Generated by scripts/sync-abis.mjs from contracts/out. Do not edit.\n` +
    `export const ${name[0].toLowerCase() + name.slice(1)}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(join(dest, `${name}.ts`), body);
}
console.log(`ABIs synced: ${contracts.join(", ")}`);
